"use client";

import { useActionState, useEffect, useRef, useState } from "react";
import {
  Dropdown,
  DropdownItem,
  DropdownMenu,
  DropdownPopover,
  DropdownTrigger,
} from "@heroui/react";

import type { Artifact } from "@/lib/artifacts";

import {
  addComment,
  addTagToArtifact,
  assignCategory,
  deleteArtifact,
  deleteComment,
  listComments,
  removeTagFromArtifact,
  unassignCategory,
  type AddCommentState,
  type CommentRow,
} from "./actions";
import {
  discardAiEdit,
  editImageArtifact,
  getAiQuota,
  keepRemixSelections,
  remixImageArtifact,
  type AiQuotaStatus,
  type EditImageState,
  type RemixImageState,
  type RemixVariant,
} from "./ai-edit-actions";

const SERIF =
  '"Cochin", "Hoefler Text", "Iowan Old Style", "Palatino Linotype", Georgia, serif';
const HAND =
  '"Marker Felt", "Bradley Hand", "Chalkboard SE", "Comic Sans MS", system-ui, sans-serif';

type Category = { id: string; name: string };
type Tag = { id: string; name: string };
type Provenance = {
  address: string | null;
  city: string | null;
  state: string | null;
  sourceUrl: string;
};
type PanelKind = null | "categorize" | "tags" | "comments" | "ai-edit";

export function ArtifactCard({
  artifact,
  boardId,
  signedImageUrl,
  categories,
  memberCategoryIds,
  tags,
  allTags,
  provenance,
  canEdit,
}: {
  artifact: Artifact;
  boardId: string;
  signedImageUrl?: string;
  categories: Category[];
  memberCategoryIds: string[];
  tags: Tag[];
  allTags: Tag[];
  provenance?: Provenance;
  canEdit: boolean;
}) {
  const [openPanel, setOpenPanel] = useState<PanelKind>(null);
  const formRef = useRef<HTMLFormElement>(null);

  return (
    <div className="group relative">
      {/* Hidden form for the Remove action */}
      {canEdit && (
        <form
          ref={formRef}
          action={deleteArtifact}
          className="hidden"
          aria-hidden="true"
        >
          <input type="hidden" name="id" value={artifact.id} />
          <input type="hidden" name="boardId" value={boardId} />
        </form>
      )}

      {canEdit && (
        <CardOverflowMenu
          kind={artifact.kind}
          onOpenPanel={setOpenPanel}
          onRemove={() => formRef.current?.requestSubmit()}
        />
      )}

      <CardBody
        artifact={artifact}
        signedImageUrl={signedImageUrl}
        provenance={provenance}
      />

      {tags.length > 0 && <TagsRow tags={tags} />}

      {openPanel && (
        <CardPanelDialog
          openPanel={openPanel}
          onClose={() => setOpenPanel(null)}
          artifact={artifact}
          boardId={boardId}
          categories={categories}
          memberCategoryIds={memberCategoryIds}
          tags={tags}
          allTags={allTags}
        />
      )}
    </div>
  );
}

function CardOverflowMenu({
  kind,
  onOpenPanel,
  onRemove,
}: {
  kind: Artifact["kind"];
  onOpenPanel: (panel: PanelKind) => void;
  onRemove: () => void;
}) {
  return (
    <Dropdown>
      <DropdownTrigger
        aria-label="Card options"
        // On hover-capable pointer devices the trigger fades in only when
        // the card is hovered/focused (keeps the canvas feeling clean).
        // On touch devices (`hover: none`) `:hover` never fires reliably,
        // so force the trigger to be always visible there.
        className="absolute right-2 top-2 z-10 inline-flex h-9 w-9 items-center justify-center rounded-full bg-white/85 text-stone-600 shadow-sm backdrop-blur-sm transition-opacity hover:text-stone-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-stone-400 [@media(hover:hover)]:opacity-0 [@media(hover:hover)]:group-hover:opacity-100 [@media(hover:hover)]:group-focus-within:opacity-100 [@media(hover:hover)]:focus-visible:opacity-100"
      >
        <svg
          width="14"
          height="14"
          viewBox="0 0 16 16"
          fill="currentColor"
          aria-hidden="true"
        >
          <circle cx="3" cy="8" r="1.5" />
          <circle cx="8" cy="8" r="1.5" />
          <circle cx="13" cy="8" r="1.5" />
        </svg>
      </DropdownTrigger>
      <DropdownPopover placement="bottom end">
        <DropdownMenu aria-label="Card actions">
          <DropdownItem onAction={() => onOpenPanel("categorize")}>
            Categorize…
          </DropdownItem>
          <DropdownItem onAction={() => onOpenPanel("tags")}>Tags…</DropdownItem>
          <DropdownItem onAction={() => onOpenPanel("comments")}>
            Comments
          </DropdownItem>
          {kind === "image" && (
            <DropdownItem onAction={() => onOpenPanel("ai-edit")}>
              AI edit…
            </DropdownItem>
          )}
          <DropdownItem variant="danger" onAction={onRemove}>
            Remove
          </DropdownItem>
        </DropdownMenu>
      </DropdownPopover>
    </Dropdown>
  );
}

/**
 * Small "AI" provenance badge rendered over the top-left of an image
 * artifact when it was generated by an AI edit/remix. Sparkle SVG is a
 * generic four-point star — same iconography Google uses for Gemini, but
 * drawn ourselves to avoid any trademark concerns.
 */
function AiBadge() {
  return (
    <span
      title="Generated with AI"
      aria-label="AI-generated"
      className="pointer-events-none absolute left-2 top-2 inline-flex items-center gap-1 rounded-full bg-stone-900/80 px-2 py-0.5 text-[9px] font-semibold uppercase tracking-wider text-stone-50 shadow-sm backdrop-blur-sm"
      style={{ letterSpacing: "0.12em" }}
    >
      <SparkleIcon />
      AI
    </span>
  );
}

function SparkleIcon({ className = "h-3 w-3" }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="currentColor"
      aria-hidden="true"
      className={className}
    >
      {/* Two overlapping four-point stars give the "Gemini sparkle" look. */}
      <path d="M12 2 L13.6 9 L20 11 L13.6 13 L12 20 L10.4 13 L4 11 L10.4 9 Z" />
      <path
        d="M19 4 L19.7 6.3 L22 7 L19.7 7.7 L19 10 L18.3 7.7 L16 7 L18.3 6.3 Z"
        opacity="0.7"
      />
    </svg>
  );
}

function TagsRow({ tags }: { tags: Tag[] }) {
  const visible = tags.slice(0, 4);
  const extra = tags.length - visible.length;
  return (
    <div className="mt-2 flex flex-wrap gap-1 px-1">
      {visible.map((t) => (
        <span
          key={t.id}
          className="rounded-full bg-stone-100 px-2 py-0.5 text-[10px] font-medium uppercase tracking-wide text-stone-600"
          style={{ letterSpacing: "0.08em" }}
        >
          {t.name}
        </span>
      ))}
      {extra > 0 && (
        <span className="px-1 text-[10px] uppercase tracking-wide text-stone-400">
          +{extra}
        </span>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Card body — discriminated union renderer
// ---------------------------------------------------------------------------

function CardBody({
  artifact,
  signedImageUrl,
  provenance,
}: {
  artifact: Artifact;
  signedImageUrl?: string;
  provenance?: Provenance;
}) {
  switch (artifact.kind) {
    case "image":
      return (
        <ImageBody
          artifact={artifact}
          signedImageUrl={signedImageUrl}
          provenance={provenance}
        />
      );
    case "link":
      return <LinkBody artifact={artifact} />;
    case "text":
      return <TextBody artifact={artifact} />;
    case "note":
      return <NoteBody artifact={artifact} />;
  }
}

function ImageBody({
  artifact,
  signedImageUrl,
  provenance,
}: {
  artifact: Extract<Artifact, { kind: "image" }>;
  signedImageUrl?: string;
  provenance?: Provenance;
}) {
  const provenanceLabel = provenance ? formatProvenance(provenance) : null;
  const [zoomed, setZoomed] = useState(false);
  const isAiEdited = !!artifact.aiEditOf;
  return (
    <figure>
      <div className="relative overflow-hidden rounded-xl bg-stone-100 shadow-[0_2px_24px_-10px_rgba(0,0,0,0.25)]">
        {signedImageUrl ? (
          <button
            type="button"
            onClick={() => setZoomed(true)}
            aria-label="Zoom image"
            className="block w-full cursor-zoom-in"
          >
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={signedImageUrl}
              alt={artifact.body || "Board image"}
              className="block h-auto w-full"
              loading="lazy"
              draggable={false}
            />
          </button>
        ) : (
          <div className="aspect-square animate-pulse" />
        )}
        {isAiEdited && <AiBadge />}
      </div>
      {zoomed && signedImageUrl && (
        <ImageZoomDialog
          src={signedImageUrl}
          alt={artifact.body || "Board image"}
          caption={artifact.body}
          onClose={() => setZoomed(false)}
        />
      )}
      {artifact.body && (
        <figcaption
          style={{ fontFamily: SERIF }}
          className="mt-3 px-1 text-[13px] italic leading-snug text-stone-500"
        >
          {artifact.body}
        </figcaption>
      )}
      {provenanceLabel && (
        <p
          className="mt-2 px-1 text-[10px] uppercase tracking-[0.18em] text-amber-700/80"
          style={{ letterSpacing: "0.18em" }}
        >
          <a
            href={provenance!.sourceUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="hover:text-amber-900"
          >
            from {provenanceLabel}
          </a>
        </p>
      )}
    </figure>
  );
}

function formatProvenance(p: Provenance): string {
  const street = p.address?.trim();
  const cityState = [p.city, p.state].filter(Boolean).join(", ");
  if (street && cityState) return `${street}, ${cityState}`;
  if (street) return street;
  if (cityState) return cityState;
  try {
    return new URL(p.sourceUrl).host.replace(/^www\./, "");
  } catch {
    return "listing";
  }
}

function LinkBody({
  artifact,
}: {
  artifact: Extract<Artifact, { kind: "link" }>;
}) {
  let host = "";
  try {
    host = new URL(artifact.url).host.replace(/^www\./, "");
  } catch {
    host = artifact.url;
  }

  const { title, description, imageUrl } = artifact.metadata;

  return (
    <article className="overflow-hidden rounded-xl border border-stone-200 bg-white transition-shadow duration-300 hover:shadow-[0_8px_28px_-12px_rgba(0,0,0,0.18)]">
      <a
        href={artifact.url}
        target="_blank"
        rel="noopener noreferrer"
        className="block"
        draggable={false}
      >
        {imageUrl && (
          <div className="aspect-[16/10] overflow-hidden bg-stone-100">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={imageUrl}
              alt=""
              className="h-full w-full object-cover transition-transform duration-700 hover:scale-[1.04]"
              loading="lazy"
              draggable={false}
            />
          </div>
        )}
        <div className="space-y-2 px-4 pb-4 pt-3.5">
          {title ? (
            <h3 className="text-[15px] font-semibold leading-snug text-stone-900">
              {title}
            </h3>
          ) : (
            <h3
              style={{ fontFamily: SERIF }}
              className="text-[15px] italic leading-snug text-stone-700"
            >
              Untitled link
            </h3>
          )}
          {description && (
            <p className="line-clamp-2 text-[13px] leading-relaxed text-stone-600">
              {description}
            </p>
          )}
          <p
            className="pt-1 font-mono text-[10px] uppercase text-amber-700/80"
            style={{ letterSpacing: "0.18em" }}
          >
            {host}
          </p>
        </div>
      </a>
    </article>
  );
}

function TextBody({
  artifact,
}: {
  artifact: Extract<Artifact, { kind: "text" }>;
}) {
  return (
    <article className="rounded-xl border border-stone-200/80 bg-stone-50/60 px-6 pb-5 pt-4">
      <div style={{ fontFamily: SERIF }} className="relative text-stone-800">
        <span
          aria-hidden="true"
          className="absolute -left-1 -top-2 select-none text-5xl leading-none text-amber-700/35"
        >
          &ldquo;
        </span>
        <p className="relative pl-4 text-[15px] italic leading-relaxed">
          {artifact.body}
        </p>
      </div>
    </article>
  );
}

function tiltFor(id: string): string {
  const hash = id
    .split("")
    .reduce((acc, ch) => (acc * 31 + ch.charCodeAt(0)) >>> 0, 0);
  const buckets = [-1.4, -0.8, -0.3, 0.3, 0.8, 1.4];
  return `${buckets[hash % buckets.length]}deg`;
}

function NoteBody({
  artifact,
}: {
  artifact: Extract<Artifact, { kind: "note" }>;
}) {
  return (
    <article
      className="rounded-md p-4 shadow-[2px_3px_14px_-7px_rgba(0,0,0,0.3)]"
      style={{
        background:
          "linear-gradient(145deg, #FFF6D8 0%, #FCEDB7 60%, #F8E29A 100%)",
        transform: `rotate(${tiltFor(artifact.id)})`,
      }}
    >
      <p
        className="whitespace-pre-line text-[15px] leading-snug text-stone-800"
        style={{ fontFamily: HAND }}
      >
        {artifact.body}
      </p>
    </article>
  );
}

// ---------------------------------------------------------------------------
// Panel modal (native <dialog>) — Categorize / Tags / Comments
// ---------------------------------------------------------------------------

function CardPanelDialog({
  openPanel,
  onClose,
  artifact,
  boardId,
  categories,
  memberCategoryIds,
  tags,
  allTags,
}: {
  openPanel: PanelKind;
  onClose: () => void;
  artifact: Artifact;
  boardId: string;
  categories: Category[];
  memberCategoryIds: string[];
  tags: Tag[];
  allTags: Tag[];
}) {
  const ref = useRef<HTMLDialogElement>(null);

  useEffect(() => {
    const dlg = ref.current;
    if (!dlg) return;
    if (openPanel) {
      if (!dlg.open) dlg.showModal();
    } else {
      if (dlg.open) dlg.close();
    }
  }, [openPanel]);

  const title =
    openPanel === "categorize"
      ? "Categorize"
      : openPanel === "tags"
        ? "Tags"
        : openPanel === "ai-edit"
          ? "AI edit"
          : "Comments";

  return (
    <dialog
      ref={ref}
      onClose={onClose}
      onClick={(e) => {
        // Close on backdrop click (target === dialog itself)
        if (e.target === ref.current) onClose();
      }}
      // The dialog is a descendant of a dnd-kit SortableCardWrapper. Native
      // <dialog showModal()> moves rendering to the top layer but pointer
      // events still bubble through React's tree, so without stopping them
      // dnd-kit interprets clicks inside the modal as drag-starts on the
      // card behind it. Eat pointer events at the dialog boundary.
      onPointerDown={(e) => e.stopPropagation()}
      onPointerMove={(e) => e.stopPropagation()}
      onPointerUp={(e) => e.stopPropagation()}
      className="m-0 mx-auto my-auto max-h-[90dvh] rounded-2xl border border-stone-200 bg-white p-0 shadow-2xl backdrop:bg-stone-900/30 backdrop:backdrop-blur-sm"
    >
      <div className="w-[min(420px,95vw)] max-h-[85dvh] overflow-y-auto p-5 sm:p-6">
        <div className="mb-4 flex items-center justify-between">
          <h3
            style={{ fontFamily: SERIF }}
            className="text-2xl font-normal text-stone-900"
          >
            {title}
          </h3>
          <button
            type="button"
            onClick={onClose}
            aria-label="Close"
            className="rounded-full p-1 text-stone-400 hover:bg-stone-100 hover:text-stone-700"
          >
            <svg
              width="18"
              height="18"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
            >
              <path d="M6 6 L18 18 M18 6 L6 18" />
            </svg>
          </button>
        </div>

        {openPanel === "categorize" && (
          <CategorizePanel
            artifactId={artifact.id}
            boardId={boardId}
            categories={categories}
            memberCategoryIds={memberCategoryIds}
          />
        )}
        {openPanel === "tags" && (
          <TagsPanel
            artifactId={artifact.id}
            boardId={boardId}
            tags={tags}
            allTags={allTags}
          />
        )}
        {openPanel === "comments" && (
          <CommentsPanel artifactId={artifact.id} boardId={boardId} />
        )}
        {openPanel === "ai-edit" && artifact.kind === "image" && (
          <AiEditPanel
            artifactId={artifact.id}
            boardId={boardId}
            onDone={onClose}
          />
        )}
      </div>
    </dialog>
  );
}

function CategorizePanel({
  artifactId,
  boardId,
  categories,
  memberCategoryIds,
}: {
  artifactId: string;
  boardId: string;
  categories: Category[];
  memberCategoryIds: string[];
}) {
  const memberSet = new Set(memberCategoryIds);
  const [pending, setPending] = useState<string | null>(null);

  async function toggle(categoryId: string) {
    setPending(categoryId);
    try {
      if (memberSet.has(categoryId)) {
        await unassignCategory({ artifactId, categoryId, boardId });
      } else {
        await assignCategory({ artifactId, categoryId, boardId });
      }
    } finally {
      setPending(null);
    }
  }

  if (categories.length === 0) {
    return (
      <p className="text-sm italic text-stone-500" style={{ fontFamily: SERIF }}>
        No categories yet. Add one from the categories section above the canvas.
      </p>
    );
  }

  return (
    <div className="flex flex-wrap gap-2">
      {categories.map((c) => {
        const on = memberSet.has(c.id);
        return (
          <button
            key={c.id}
            type="button"
            onClick={() => toggle(c.id)}
            disabled={pending === c.id}
            className={`rounded-full border px-3 py-1.5 text-sm transition-colors ${
              on
                ? "border-stone-900 bg-stone-900 text-stone-50"
                : "border-stone-200 bg-white text-stone-700 hover:border-stone-400"
            } ${pending === c.id ? "opacity-50" : ""}`}
          >
            {c.name}
          </button>
        );
      })}
    </div>
  );
}

function TagsPanel({
  artifactId,
  boardId,
  tags,
  allTags,
}: {
  artifactId: string;
  boardId: string;
  tags: Tag[];
  allTags: Tag[];
}) {
  const [draft, setDraft] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [pending, setPending] = useState(false);

  const tagIds = new Set(tags.map((t) => t.id));
  const suggestions = allTags
    .filter((t) => !tagIds.has(t.id))
    .filter(
      (t) =>
        draft.length > 0 && t.name.toLowerCase().includes(draft.toLowerCase()),
    )
    .slice(0, 6);

  async function add(name: string) {
    const value = name.trim();
    if (!value) return;
    setPending(true);
    setError(null);
    const result = await addTagToArtifact({
      boardId,
      artifactId,
      tagName: value,
    });
    setPending(false);
    if ("error" in result) {
      setError(result.error);
      return;
    }
    setDraft("");
  }

  async function remove(tagId: string) {
    await removeTagFromArtifact({ boardId, artifactId, tagId });
  }

  return (
    <div className="flex flex-col gap-3">
      <div className="flex flex-wrap gap-1.5">
        {tags.length === 0 && (
          <p
            className="text-sm italic text-stone-500"
            style={{ fontFamily: SERIF }}
          >
            No tags yet.
          </p>
        )}
        {tags.map((t) => (
          <span
            key={t.id}
            className="inline-flex items-center gap-1 rounded-full bg-stone-100 py-1 pl-3 pr-1 text-xs text-stone-700"
          >
            {t.name}
            <button
              type="button"
              onClick={() => remove(t.id)}
              aria-label={`Remove ${t.name}`}
              className="ml-1 inline-flex h-5 w-5 items-center justify-center rounded-full text-stone-400 hover:bg-stone-200 hover:text-stone-700"
            >
              ×
            </button>
          </span>
        ))}
      </div>

      <form
        onSubmit={(e) => {
          e.preventDefault();
          void add(draft);
        }}
        className="relative"
      >
        <input
          type="text"
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          placeholder="Type a tag and press Enter…"
          maxLength={40}
          className="w-full rounded-lg border border-stone-200 bg-white px-3 py-2 text-sm text-stone-900 placeholder:text-stone-400 focus:border-stone-400 focus:outline-none focus:ring-2 focus:ring-stone-200"
          disabled={pending}
        />
        {suggestions.length > 0 && (
          <ul className="absolute left-0 right-0 top-full z-10 mt-1 max-h-44 overflow-auto rounded-lg border border-stone-200 bg-white shadow-lg">
            {suggestions.map((s) => (
              <li key={s.id}>
                <button
                  type="button"
                  onClick={() => void add(s.name)}
                  className="block w-full px-3 py-1.5 text-left text-sm text-stone-700 hover:bg-stone-50"
                >
                  {s.name}
                </button>
              </li>
            ))}
          </ul>
        )}
      </form>
      {error && <p className="text-sm text-red-700">{error}</p>}
    </div>
  );
}

function CommentsPanel({
  artifactId,
  boardId,
}: {
  artifactId: string;
  boardId: string;
}) {
  const [comments, setComments] = useState<CommentRow[] | null>(null);
  const [reloadKey, setReloadKey] = useState(0);

  useEffect(() => {
    let cancelled = false;
    listComments({ artifactId }).then((rows) => {
      if (!cancelled) setComments(rows);
    });
    return () => {
      cancelled = true;
    };
  }, [artifactId, reloadKey]);

  return (
    <div className="flex flex-col gap-4">
      <div className="max-h-64 overflow-y-auto pr-1">
        {comments === null ? (
          <p className="text-sm text-stone-400">Loading…</p>
        ) : comments.length === 0 ? (
          <p className="text-sm italic text-stone-500" style={{ fontFamily: SERIF }}>
            Be the first to comment.
          </p>
        ) : (
          <ul className="space-y-3">
            {comments.map((c) => (
              <li
                key={c.id}
                className="rounded-md border border-stone-100 bg-stone-50 p-3"
              >
                <p className="whitespace-pre-line text-[14px] leading-relaxed text-stone-800">
                  {c.body}
                </p>
                <div className="mt-2 flex items-center justify-between">
                  <span className="text-[10px] uppercase tracking-wide text-stone-400">
                    {new Date(c.created_at).toLocaleDateString()}
                  </span>
                  <DeleteCommentButton
                    id={c.id}
                    boardId={boardId}
                    onDeleted={() => setReloadKey((k) => k + 1)}
                  />
                </div>
              </li>
            ))}
          </ul>
        )}
      </div>

      <CommentForm
        artifactId={artifactId}
        boardId={boardId}
        onAdded={() => setReloadKey((k) => k + 1)}
      />
    </div>
  );
}

function DeleteCommentButton({
  id,
  boardId,
  onDeleted,
}: {
  id: string;
  boardId: string;
  onDeleted: () => void;
}) {
  return (
    <form
      action={async (fd) => {
        await deleteComment(fd);
        onDeleted();
      }}
    >
      <input type="hidden" name="id" value={id} />
      <input type="hidden" name="boardId" value={boardId} />
      <button
        type="submit"
        className="text-[10px] uppercase tracking-wide text-stone-400 hover:text-red-700"
      >
        Delete
      </button>
    </form>
  );
}

function CommentForm({
  artifactId,
  boardId,
  onAdded,
}: {
  artifactId: string;
  boardId: string;
  onAdded: () => void;
}) {
  const [error, setError] = useState<string | null>(null);
  const [pending, setPending] = useState(false);
  const formRef = useRef<HTMLFormElement>(null);

  return (
    <form
      ref={formRef}
      action={async (fd) => {
        setPending(true);
        setError(null);
        const initial: AddCommentState = { status: "idle" };
        const result = await addComment(initial, fd);
        setPending(false);
        if (result.status === "error") {
          setError(result.message);
          return;
        }
        formRef.current?.reset();
        onAdded();
      }}
      className="flex flex-col gap-2"
    >
      <input type="hidden" name="boardId" value={boardId} />
      <input type="hidden" name="artifactId" value={artifactId} />
      <textarea
        name="body"
        rows={2}
        maxLength={2000}
        placeholder="Add a comment…"
        required
        className="w-full rounded-lg border border-stone-200 bg-white px-3 py-2 text-sm text-stone-900 placeholder:text-stone-400 focus:border-stone-400 focus:outline-none focus:ring-2 focus:ring-stone-200"
        disabled={pending}
      />
      {error && <p className="text-sm text-red-700">{error}</p>}
      <div>
        <button
          type="submit"
          disabled={pending}
          className="rounded-md bg-stone-900 px-3 py-1.5 text-xs uppercase tracking-wider text-stone-50 disabled:opacity-50"
          style={{ letterSpacing: "0.12em" }}
        >
          {pending ? "Posting…" : "Post"}
        </button>
      </div>
    </form>
  );
}

type ZoomAction = {
  label: string;
  onClick: () => void;
  variant?: "primary" | "danger" | "ghost";
  disabled?: boolean;
};

function ImageZoomDialog({
  src,
  alt,
  caption,
  onClose,
  actions,
}: {
  src: string;
  alt: string;
  caption?: string;
  onClose: () => void;
  /**
   * Optional action buttons. When provided, replaces the click-to-close
   * behavior on the image (so the user can't accidentally dismiss a
   * generated edit) — the explicit action buttons are the only way out
   * besides Esc / backdrop / X.
   */
  actions?: ZoomAction[];
}) {
  const ref = useRef<HTMLDialogElement>(null);

  useEffect(() => {
    const dlg = ref.current;
    if (!dlg) return;
    if (!dlg.open) dlg.showModal();
    return () => {
      if (dlg.open) dlg.close();
    };
  }, []);

  const hasActions = !!actions && actions.length > 0;

  return (
    <dialog
      ref={ref}
      onClose={onClose}
      onClick={(e) => {
        if (e.target === ref.current) onClose();
      }}
      onPointerDown={(e) => e.stopPropagation()}
      onPointerMove={(e) => e.stopPropagation()}
      onPointerUp={(e) => e.stopPropagation()}
      className="m-0 mx-auto my-auto max-h-[95dvh] max-w-[95vw] rounded-xl border-0 bg-transparent p-0 backdrop:bg-stone-900/80 backdrop:backdrop-blur-sm"
    >
      <div className="flex flex-col items-center gap-3">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={src}
          alt={alt}
          onClick={hasActions ? undefined : onClose}
          className={`block max-h-[80dvh] w-auto max-w-[95vw] rounded-xl object-contain shadow-2xl ${
            hasActions ? "" : "cursor-zoom-out"
          }`}
          draggable={false}
        />
        {caption && (
          <figcaption
            style={{ fontFamily: SERIF }}
            className="max-w-[80vw] px-2 text-center text-sm italic leading-snug text-stone-100"
          >
            {caption}
          </figcaption>
        )}
        {hasActions && (
          <div className="mt-1 flex flex-wrap items-center justify-center gap-2">
            {actions!.map((a) => (
              <button
                key={a.label}
                type="button"
                onClick={a.onClick}
                disabled={a.disabled}
                className={zoomActionClass(a.variant)}
                style={{ letterSpacing: "0.12em" }}
              >
                {a.label}
              </button>
            ))}
          </div>
        )}
        <button
          type="button"
          onClick={onClose}
          aria-label="Close"
          className="absolute right-3 top-3 inline-flex h-8 w-8 items-center justify-center rounded-full bg-white/10 text-white backdrop-blur-sm hover:bg-white/20"
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
            <path d="M6 6 L18 18 M18 6 L6 18" />
          </svg>
        </button>
      </div>
    </dialog>
  );
}

function zoomActionClass(variant: ZoomAction["variant"]): string {
  const base =
    "rounded-md px-4 py-2 text-xs uppercase disabled:opacity-50 transition-colors";
  switch (variant) {
    case "primary":
      return `${base} bg-stone-50 text-stone-900 hover:bg-white`;
    case "danger":
      return `${base} bg-red-600/90 text-white hover:bg-red-600`;
    default:
      return `${base} bg-white/10 text-white hover:bg-white/20`;
  }
}

const editImageInitial: EditImageState = { status: "idle" };
const remixImageInitial: RemixImageState = { status: "idle" };

function AiEditPanel({
  artifactId,
  boardId,
  onDone,
}: {
  artifactId: string;
  boardId: string;
  onDone: () => void;
}) {
  const [quota, setQuota] = useState<AiQuotaStatus | null>(null);
  const [variants, setVariants] = useState(1);
  const [reviewDismissed, setReviewDismissed] = useState(false);
  const [discarding, setDiscarding] = useState(false);
  const [editState, editAction, editPending] = useActionState(
    editImageArtifact,
    editImageInitial,
  );
  const [remixState, remixAction, remixPending] = useActionState(
    remixImageArtifact,
    remixImageInitial,
  );

  useEffect(() => {
    let cancelled = false;
    getAiQuota().then((q) => {
      if (!cancelled) setQuota(q);
    });
    return () => {
      cancelled = true;
    };
  }, []);

  const isRemix = variants > 1;
  const action = isRemix ? remixAction : editAction;
  const pending = isRemix ? remixPending : editPending;

  // Reviews — only one can be active at a time (the other path's state
  // sticks around but we hide it).
  const showingEditReview =
    !isRemix &&
    editState.status === "done" &&
    !reviewDismissed &&
    !!editState.signedUrl;
  const showingRemixReview =
    isRemix && remixState.status === "done" && !reviewDismissed;

  const errorMessage =
    editState.status === "error"
      ? editState.message
      : remixState.status === "error"
        ? remixState.message
        : null;

  const remainingNumber = quota?.exempt
    ? null
    : quota
      ? Math.max(0, quota.remaining ?? 0)
      : null;
  const remainingDisplay = quota?.exempt
    ? "∞"
    : quota
      ? Math.max(0, quota.remaining ?? 0).toString()
      : "…";
  const atLimit =
    !!quota && !quota.exempt && (quota.remaining ?? 0) <= 0;
  const remixWouldOverrun =
    !!quota && !quota.exempt && variants > (quota.remaining ?? 0);

  async function refreshQuota() {
    const q = await getAiQuota();
    setQuota(q);
  }

  async function handleDiscard() {
    if (editState.status !== "done") return;
    setDiscarding(true);
    try {
      await discardAiEdit({
        boardId,
        outputArtifactId: editState.outputArtifactId,
      });
      await refreshQuota();
      setReviewDismissed(true);
    } finally {
      setDiscarding(false);
    }
  }

  async function handleRemixConfirm(keepIds: string[]) {
    if (remixState.status !== "done") return;
    const allIds = remixState.results.map((r) => r.outputArtifactId);
    const keepSet = new Set(keepIds);
    const discard = allIds.filter((id) => !keepSet.has(id));
    setDiscarding(true);
    try {
      await keepRemixSelections({
        boardId,
        keepArtifactIds: keepIds,
        discardArtifactIds: discard,
      });
      await refreshQuota();
      setReviewDismissed(true);
      onDone();
    } finally {
      setDiscarding(false);
    }
  }

  const lastPrompt =
    isRemix && remixState.status === "done"
      ? remixState.prompt
      : editState.status === "done"
        ? editState.prompt
        : undefined;

  return (
    <>
      <form action={action} className="flex flex-col gap-3">
        <input type="hidden" name="boardId" value={boardId} />
        <input type="hidden" name="artifactId" value={artifactId} />
        <input type="hidden" name="variants" value={variants} />

        <p className="text-[11px] uppercase tracking-wide text-stone-500">
          {remainingDisplay} of {quota?.limit ?? "10"}{" "}
          {quota?.exempt ? "edits" : "edits left this week"}
        </p>

        <textarea
          name="prompt"
          rows={3}
          maxLength={1000}
          required
          placeholder={
            isRemix
              ? "e.g. Different cabinet colors — white, navy, walnut"
              : "e.g. Add a small pool with a tanning ledge to the backyard"
          }
          disabled={pending || atLimit}
          defaultValue={lastPrompt}
          className="w-full rounded-lg border border-stone-200 bg-white px-3 py-2 text-sm text-stone-900 placeholder:text-stone-400 focus:border-stone-400 focus:outline-none focus:ring-2 focus:ring-stone-200 disabled:bg-stone-50"
        />

        <div className="flex flex-wrap items-center gap-2">
          <span className="text-[10px] uppercase tracking-wider text-stone-500">
            Variants
          </span>
          <div className="inline-flex gap-1 rounded-full border border-stone-200 bg-white p-0.5">
            {[1, 2, 3, 4].map((n) => {
              const blocked =
                !!quota &&
                !quota.exempt &&
                remainingNumber !== null &&
                n > remainingNumber;
              return (
                <button
                  key={n}
                  type="button"
                  onClick={() => setVariants(n)}
                  aria-pressed={variants === n}
                  disabled={pending || blocked}
                  title={
                    blocked
                      ? `Only ${remainingNumber} edit${remainingNumber === 1 ? "" : "s"} left this week`
                      : undefined
                  }
                  className={`rounded-full px-2.5 py-1 text-xs transition-colors ${
                    variants === n
                      ? "bg-stone-900 text-stone-50"
                      : "text-stone-500 hover:text-stone-900 disabled:opacity-30"
                  }`}
                >
                  {n}
                </button>
              );
            })}
          </div>
          <span className="text-[11px] text-stone-500">
            {variants === 1
              ? "single edit"
              : `remix — ${variants} variants, uses ${variants} of your quota`}
          </span>
        </div>

        {errorMessage && (
          <p className="text-sm text-red-700">{errorMessage}</p>
        )}
        {atLimit && !errorMessage && (
          <p className="text-sm text-amber-700">
            You&apos;ve used your weekly AI edit quota. The counter resets on a
            rolling 7-day window.
          </p>
        )}

        <div className="flex items-center justify-end gap-2">
          <button
            type="submit"
            disabled={pending || atLimit || remixWouldOverrun}
            className="rounded-md bg-stone-900 px-3 py-1.5 text-xs uppercase tracking-wider text-stone-50 disabled:opacity-50"
            style={{ letterSpacing: "0.12em" }}
          >
            {pending
              ? isRemix
                ? `Generating ${variants}…`
                : "Editing…"
              : isRemix
                ? `Generate ${variants}`
                : "Generate"}
          </button>
        </div>
      </form>

      {showingEditReview && editState.status === "done" && editState.signedUrl && (
        <ImageZoomDialog
          src={editState.signedUrl}
          alt="AI edit preview"
          caption={editState.prompt}
          onClose={() => setReviewDismissed(true)}
          actions={[
            {
              label: discarding ? "Discarding…" : "Discard & retry",
              variant: "danger",
              onClick: handleDiscard,
              disabled: discarding,
            },
            {
              label: "Keep",
              variant: "primary",
              onClick: onDone,
              disabled: discarding,
            },
          ]}
        />
      )}

      {showingRemixReview && remixState.status === "done" && (
        <RemixGalleryDialog
          variants={remixState.results}
          requested={remixState.requested}
          failed={remixState.failed}
          prompt={remixState.prompt}
          pending={discarding}
          onClose={() => setReviewDismissed(true)}
          onConfirm={handleRemixConfirm}
          onDiscardAll={() => handleRemixConfirm([])}
        />
      )}
    </>
  );
}

function RemixGalleryDialog({
  variants,
  requested,
  failed,
  prompt,
  pending,
  onClose,
  onConfirm,
  onDiscardAll,
}: {
  variants: RemixVariant[];
  requested: number;
  failed: number;
  prompt: string;
  pending: boolean;
  onClose: () => void;
  onConfirm: (keepArtifactIds: string[]) => void;
  onDiscardAll: () => void;
}) {
  const ref = useRef<HTMLDialogElement>(null);
  const [selected, setSelected] = useState<Record<string, boolean>>(() =>
    Object.fromEntries(variants.map((v) => [v.outputArtifactId, true])),
  );
  const [zoomedId, setZoomedId] = useState<string | null>(null);

  useEffect(() => {
    const dlg = ref.current;
    if (!dlg) return;
    if (!dlg.open) dlg.showModal();
    return () => {
      if (dlg.open) dlg.close();
    };
  }, []);

  const keepCount = Object.values(selected).filter(Boolean).length;
  const zoomed = zoomedId
    ? variants.find((v) => v.outputArtifactId === zoomedId)
    : null;
  const keepIds = variants
    .filter((v) => selected[v.outputArtifactId])
    .map((v) => v.outputArtifactId);

  return (
    <dialog
      ref={ref}
      onClose={onClose}
      onClick={(e) => {
        if (e.target === ref.current) onClose();
      }}
      onPointerDown={(e) => e.stopPropagation()}
      onPointerMove={(e) => e.stopPropagation()}
      onPointerUp={(e) => e.stopPropagation()}
      className="m-0 mx-auto my-auto max-h-[95dvh] w-[min(900px,95vw)] rounded-xl border-0 bg-stone-900 p-0 shadow-2xl backdrop:bg-stone-900/80 backdrop:backdrop-blur-sm"
    >
      <div className="flex flex-col gap-4 p-5 sm:p-6">
        <div className="flex flex-wrap items-baseline justify-between gap-2">
          <div>
            <p className="text-[10px] uppercase tracking-[0.18em] text-stone-400">
              Pick which to keep
            </p>
            <p
              style={{ fontFamily: SERIF }}
              className="mt-0.5 text-base italic leading-snug text-stone-100"
            >
              {prompt}
            </p>
          </div>
          <p className="text-[11px] uppercase tracking-wide text-stone-400">
            {keepCount} of {variants.length} selected
            {failed > 0 ? ` · ${failed} of ${requested} failed` : ""}
          </p>
        </div>

        <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4">
          {variants.map((v) => {
            const isOn = !!selected[v.outputArtifactId];
            return (
              <label
                key={v.outputArtifactId}
                // Hover scale gated to hover-capable pointers only — touch
                // devices don't have a stable :hover, and scaling on tap
                // would feel laggy. Mobile users get the magnifier button
                // (top-left) instead.
                className={`group relative cursor-pointer overflow-hidden rounded-lg border-2 transition-transform duration-200 [@media(hover:hover)]:hover:z-10 [@media(hover:hover)]:hover:scale-[1.35] ${
                  isOn
                    ? "border-stone-50 ring-2 ring-stone-300/50"
                    : "border-transparent opacity-50 hover:opacity-100"
                }`}
              >
                <input
                  type="checkbox"
                  className="sr-only"
                  checked={isOn}
                  onChange={(e) =>
                    setSelected((s) => ({
                      ...s,
                      [v.outputArtifactId]: e.target.checked,
                    }))
                  }
                />
                {v.signedUrl ? (
                  /* eslint-disable-next-line @next/next/no-img-element */
                  <img
                    src={v.signedUrl}
                    alt={`Variant ${v.variantIndex + 1}`}
                    loading="lazy"
                    className="block aspect-square w-full object-cover"
                    draggable={false}
                  />
                ) : (
                  <div className="aspect-square animate-pulse bg-stone-700" />
                )}
                {/* Magnifier button — opens a fullscreen zoom of just this
                    variant. Pointer events stop here so tapping it doesn't
                    toggle the surrounding label's checkbox. */}
                {v.signedUrl && (
                  <button
                    type="button"
                    aria-label={`Zoom variant ${v.variantIndex + 1}`}
                    onPointerDown={(e) => e.stopPropagation()}
                    onPointerUp={(e) => e.stopPropagation()}
                    onClick={(e) => {
                      e.preventDefault();
                      e.stopPropagation();
                      setZoomedId(v.outputArtifactId);
                    }}
                    className="absolute left-2 top-2 inline-flex h-7 w-7 items-center justify-center rounded-full bg-stone-900/70 text-stone-50 shadow-sm backdrop-blur-sm transition-colors hover:bg-stone-900/90"
                  >
                    <svg
                      width="14"
                      height="14"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      aria-hidden="true"
                    >
                      <circle cx="11" cy="11" r="7" />
                      <path d="m21 21-4.3-4.3" />
                      <path d="M11 8v6 M8 11h6" />
                    </svg>
                  </button>
                )}
                {isOn && (
                  <span className="absolute right-2 top-2 inline-flex h-6 w-6 items-center justify-center rounded-full bg-stone-50 text-[10px] font-bold text-stone-900">
                    ✓
                  </span>
                )}
              </label>
            );
          })}
        </div>

        {zoomed?.signedUrl && (
          <ImageZoomDialog
            src={zoomed.signedUrl}
            alt={`Variant ${zoomed.variantIndex + 1}`}
            caption={prompt}
            onClose={() => setZoomedId(null)}
          />
        )}

        <div className="flex flex-wrap items-center justify-between gap-2">
          <button
            type="button"
            onClick={onDiscardAll}
            disabled={pending}
            className="rounded-md bg-red-600/90 px-4 py-2 text-xs uppercase tracking-wider text-white hover:bg-red-600 disabled:opacity-50"
            style={{ letterSpacing: "0.12em" }}
          >
            Discard all
          </button>
          <button
            type="button"
            onClick={() => onConfirm(keepIds)}
            disabled={pending || keepCount === 0}
            className="rounded-md bg-stone-50 px-4 py-2 text-xs uppercase tracking-wider text-stone-900 hover:bg-white disabled:opacity-50"
            style={{ letterSpacing: "0.12em" }}
          >
            {pending
              ? "Saving…"
              : `Keep ${keepCount} ${keepCount === 1 ? "variant" : "variants"}`}
          </button>
        </div>

        <button
          type="button"
          onClick={onClose}
          aria-label="Close"
          className="absolute right-3 top-3 inline-flex h-8 w-8 items-center justify-center rounded-full bg-white/10 text-white backdrop-blur-sm hover:bg-white/20"
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
            <path d="M6 6 L18 18 M18 6 L6 18" />
          </svg>
        </button>
      </div>
    </dialog>
  );
}
